### ISSUE TITLE
Add a prelude

### ISSUE THREAD

**Issue by casey** [soenkehahn/cradle#115]
It might be nice to add a prelude, so users can do `use cradle::prelude::*;`.

This has some advantages:

- The existence of a `prelude` module signals to users that it should be glob-imported.
- We can add and remove things from the crate root without needing to think about whether or not they will clutter the namespace of users doing `use cradle::*;`

**Comment by soenkehahn** [comment]
I've experimented with this here: #95. It didn't go well. :/ The main problem is that even if macros are declared in `cradle::prelude`, they still show up as if they were declared in `cradle` in the root. So for this crate, where the primary interface is three macros, I don't think the `prelude` pattern is the best idea.

**Comment by casey** [comment]
I'm not sure I understand the problem. I was thinking that everything would stay where it is, but that `cradle::prelude` would contain `pub use` re-exports. Does that not work?

**Comment by soenkehahn** [comment]
Oh, I see. Yeah, that would work. Except that (I think) the `prelude` module would not contain the documentation for all the items, but just links to where they really are. I assumed that for that reason these items should be declared within `prelude`.

I wonder what this would mean for documentation and discoverability, especially for newcomers to the library. Would the main documentation (the one that's currently [in the crate root](https://docs.rs/cradle/0.0.13/cradle/)) move to `prelude`? And would the crate root documentation refer users there? Or would it remain where it is, and just switch to use `use cradle::prelude::*;` in the examples? (And then the `prelude` module would refer users to the main crate documentation.) (I think I would prefer the latter.)

And then, would the crate root not re-export anything? And then probably only contain sub-modules and macros? (Since macros get put into the crate root automatically.) That would probably not be the best way to explore the API, since I'd think `Input` and `Output` are very important. But maybe this could be mitigated by annotating the sub-modules `cradle::input` and `cradle::output`, so that a short description of what they contain shows up in the documentation in the crate root.

So yeah, to summarize, I'm a bit concerned what this would do to documentation. But with some care, I think it could be a good change.

**Comment by casey** [comment]
I think the standard way to do it is to leave the crate structure unchanged, and just have re-exports in the prelude, and leave the documentation where it is.

Everything that's exported by the prelude is still defined and exported from some other location, the crate root or wherever makes sense.

I think it actually winds up working well in terms of documentation and discovery. Documentation is unchanged, and when users to go to the docs page for the prelude, they see usually a brief comment, as well as the list of re-exports, which both link back to the original item (and its documentation) and serve as a list of the most important and commonly used types exported by the library.

Here's what it looks like for [std::io::prelude](https://doc.rust-lang.org/stable/std/io/prelude/index.html).
