### ISSUE TITLE
Avoid writing temporary files to crate root when running tests

### ISSUE THREAD

**Issue by casey** [soenkehahn/cradle#116]
Currently, the tests write files called `foo`, and also `filename with spaces` (I think) to the crate root when running tests. It would be nice to come up with a way to avoid this.

**Comment by soenkehahn** [comment]
I _think_ only the doctests write files to the repo root. I did that to be able to have simple documenting test-cases that aren't cluttered by setting up temporary directories and such. But I learned since then that we can just comment lines in the doctests to hide them from the documentation. So I think we could do something like:

```
//! ```
//! use cradle::*;
//! # in_temporary_directory({
//! cmd_unit!(%"touch foo");
//! # });
//! ```
```

**Comment by casey** [comment]
Nice, that looks good. I didn't realize you could hide lines in the middle of a doctest.
