### ISSUE TITLE
Implement `Input` for `Option<Input>`

### ISSUE THREAD

**Issue by casey** [soenkehahn/cradle#131]
This is motivated by this code snippet:

```rust
cmd_unit!(
  "foo",
  if hostname == "vagrant" {
    vec![Env("CARGO_TARGET_DIR", "/vagrant/target")]
  } else {
    vec![]
  },
);
```

If `Input` was implemented for `Option<Input>`, this could be:

```rust
cmd_unit!(
  "foo",
  if hostname == "vagrant" {
    Some(Env("CARGO_TARGET_DIR", "/vagrant/target"))
  } else {
    None
  },
);
```

which seems better. What do you think?

**Comment by casey** [comment]
Good point by @soenkehahn that this could be confusing.

This would make this:

```rust
cmd_unit!("something", std::env::var_os("FOO"));`
```

Maybe pass an argument to `something`, or maybe not, depending on whether the variable is set, which is probably not the intent.

**Comment by soenkehahn** [comment]
Yes. I think in general that input and return-type polymorphism can open up some disadvantages that are usually avoided in statically typed languages. For example you could imagine someone writing e.g. this code:

``` rust
fn foo() -> String {
  ...
}

fn bar() {
  cmd_unit!("something", foo());
}
```

And then (maybe during an attempted refactor) they change `foo` to return an `Option<String>`. And then rely on the compiler to tell them about every place in the code where they need to make adjustments. But they miss `bar`, because of the `impl<I: Input> Input for Option<I>`.

I'll close this to be on the safer side. 
(If anyone really wants this, please speak up.)
