### ISSUE TITLE
Implement Output for String

### ISSUE THREAD

**Issue by casey** [soenkehahn/cradle#189]
What do you think about implementing `Output` for string, for collecting the un-trimmed standard output? I wrote `let s: String = run_output("echo foo");` today and forgot that I needed to use `StdoutUntrimmed` to get what I wanted.

I think we talked about this, and the hesitance was that because stdout can be trimmed or untrimmed, implementing `Output` for `String` might be confusing.

I think though that it's useful and natural, so we should consider it. As for whether it should be trimmed or untrimmed, I was thinking that we'll probably wind up implementing `Output` for `Vec<u8>`, which collects stdout without converting it to a string, for commands that produce binary output. This would definitely be untrimmed, because it doesn't make sense to remove a newline from a bytestring. So, it would make sense for the `Output` implementations for `String` and `Vec<u8>` to not do any modification of the output.

**Comment by soenkehahn** [comment]
> I think we talked about this, and the hesitance was that because stdout can be trimmed or untrimmed, implementing `Output` for `String` might be confusing.

Yes, exactly. Here's some more thoughts on why I think it might be better *not* to implement `Output for String`:

I agree that it wouldn't make sense to trim whitespace from the output in that impl. `Output for String` feels like it should be very basic behavior and not do anything magical like that. But if we don't trim the output, we have the following problem:

In `bash`, it's very easy and somewhat common to use the output of one command as the input to another. For example like this:
``` bash
file $(which ls)
```
The output of `which ls` does technically contain a newline character at the end, but in `bash` everything still works out. Consider translating this snippet to `rust` with `cradle`:
``` rust
let ls: String = run_output!(%"which ls");
run!("file", ls);
```
This seems very straight-forward and like it should work, but it doesn't, because `ls` is `"/usr/bin/ls\n"`, including the newline. And it crashes at runtime.

If we don't have an `Output for String` impl, we force users to make a conscious decision about what they want. Whether they want trimmed or untrimmed output.

So I would argue that your example (where you try to use `String` as the output and the compiler doesn't let you) is `cradle` working exactly as intended. It forces you *at compile time* to make a choice. Instead of assuming that you want untrimmed output, compiling and then possibly causing weird crashes -- or worse other misbehavior -- at runtime, in case that assumption is wrong.

Of course an `Output for String` impl would be really convenient, often. I'm just not convinced it's really a good idea.

**Comment by casey** [comment]
Ahh, right, I forgot about all the commands that return output with newlines. Which is also a good indication that I would write bugs if `Input` was implemented for `String`, which I think is a good enough argument not to implement it.
