### ISSUE TITLE
Name for `CmdArgument`

### ISSUE THREAD

**Issue by casey** [soenkehahn/cradle#66]
I was thinking that `CmdArgument` might be a little ambiguous.

Everything that implements `CmdArgument` can be used as an argument to `cmd!`, however they're not all "arguments" in the sense that we think of them. Some of them set the current directory, or configure logging.

What about `Directive`?

And also, what about a different name for `prepare_config`? I was thinking that `apply` might be good.

I was thinking about this because I was thinking about adding an `Argument` trait which could be used to easily allow passing any type as an argument that implements `Display`. Something like:

```
trait Argument: ToString { }

impl CmdArgument for Argument {
  fn prepare_config(self, config: &mut Config) {
    config.arguments.push(self.to_string().into());
  }
}
```

Then, you could do things like:

```
impl Argument for u8 {}
```

And get the obvious `CmdArgument` implementation for free. But having an `Argument` trait and a `CmdArgument` trait is confusing.

**Comment by soenkehahn** [comment]
I was thinking of `CmdArgument` to mean 'possible argument to the `cmd!` macro'. But yeah, it's not great, since arguments passed into processes are also called arguments. I do like that it starts with `Cmd`, since then it's clear that it is configuring commands. So `CmdDirective`? Or `CmdConfig`, `CmdConfiguration` or `CmdOption`?

I like the idea of renaming `CmdArgument::prepare_config` into `CmdArgument::apply` in any case. I might create a PR for that. Note that there is also a `CmdOutput::prepare_config`, which would keep its name. (?)

One point about introducing an additional `Argument` trait with a blanket implementation: I try to be mindful of people that aren't that familiar with traits and don't want to spend too much time on trying to understand them better. I enjoy type-level shenanigans a lot, but some people don't. And for those people, we're already pushing the envelope a bit with both `CmdArgument` and `CmdOutput`. So at first glance it seems that forcing users that want a `impl CmdArgument for u8` to write that manually is probably better than cluttering the api with an `Argument` trait and a blanket implementation `impl<T: Argument> CmdArgument for T`.

**Comment by casey** [comment]
I think the `Cmd` prefix is a little redundant, since `cmd!` is the main and only export of `cradle`, so everything is kind of implicitly related to it. But that's just an aesthetic quibble.

- `CmdOption` - Probably not good, because of `std::option::Option`
- `CmdConfig(uration)?` - Kind of confusing when there's also `cradle::Config`

What about `InputDirective` for `CmdArgument` and `OutputDirective` for `CmdOutput`? Then both could have an `apply` method.

I agree about `Argument`. It's nice to save typing, but it doesn't save that much, and if you see it in the API, I think users will get the impression that maybe it's doing something magical, or they *have* to implement `Argument` in order to pass something to `cmd!`.

**Comment by soenkehahn** [comment]
> What about `InputDirective` for `CmdArgument` and `OutputDirective` for `CmdOutput`? Then both could have an `apply` method.

I don't think I would want to rename `CmdOutput`s `prepare_config` to `apply` even if it's called `OutputDirective`. `CmdOutput` has two methods, `prepare_config` to prepare the config before running the command, and `from_run_result` to convert the result of the command run to the output value. `prepare_config` is a bit weird, since we're using return type polymorphism to determine how the `config` should be constructed. And all that happens long before any value of the return type is involved. So I thought `prepare_config` was the clearest name for that.

Re: trait names: To me the term `Directive` doesn't seem to make anything clearer. What about just `Input` and `Output`? (Or `CmdInput` and `CmdOutput`, if we want to stick with the `Cmd...` prefix. Although you have a point that that's somewhat redundant.)

**Comment by soenkehahn** [comment]
I created #76, which just renames `CmdArgument` to `CmdInput`. I think that's already an improvement.

**Comment by casey** [comment]
Regarding our conversation offline, I think `Input` and `Output` are great. (Which I prefer to `CmdInput` and `CmdOutput`, but those are still fine.) `Input::configure` and `Output::configure` would be good method names in that case.
